# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Agent

stages:
- stage: Build
  jobs: 
  - job: firstjob
    steps:
    - bash: echo run buildjob
    - bash: echo $(PipelineLevelVariable)
  - job: secondjob
    steps:
    - bash: echo build firstjob
- stage: qadeploy
  variables:
    environment: dev
  jobs: 
  - job: firstjob
    steps:
    - bash: echo run deployjob
    - bash: echo $(environment)deployjob
  - job: secondjob
    steps:
    - bash: echo builddeploy buildjob
